---
version: "3.9"

services:
  bot-status:
    build:
      context: .
    restart: unless-stopped
    environment:
      - TOKEN_1=${TOKEN_1}
      - IP_1=${IP_1}
      - PORT_1=${PORT_1}
      - DELAY_1=${DELAY_1}
      - GAME_1=${GAME_1}
      - ACTIVITY_1=${ACTIVITY_1}
