---
version: "3.9"

services:
  bot-status:
    build:
      context: .
    restart: unless-stopped
    container_name: bot-status
    environment:
      - TOKEN=Your_Discord_Bot_Token
      - IP=Your_Server_IP
      - PORT=Your_Server_Port
      - DELAY=Amount_Of_Time_Between_Updates
      - GAME=Game_Name
      - ACTIVITY=Activity_Name