---
version: "3.9"

services:
  bot-status:
    build:
      context: .
    restart: unless-stopped
    container_name: bot-status
    environment:
      - TOKEN=${TOKEN}
      - IP=${IP}
      - PORT=${PORT}
      - DELAY=${DELAY}
      - GAME=${GAME}
      - ACTIVITY=${ACTIVITY}