---
version: "3.9"

services:
  bot-status:
    image: unclamped/bot-status:latest

    # uncomment this section if you want to build the image by yourself
    # build:
    #   context: .

    restart: unless-stopped
    environment:
      - TOKEN_1=${TOKEN_1}
      - IP_1=${IP_1}
      - PORT_1=${PORT_1}
      - DELAY_1=${DELAY_1}
      - GAME_1=${GAME_1}
      - ACTIVITY_1=${ACTIVITY_1}
